INSERT INTO users (
    id,
    nome,
    email,
    login,
    senha,
    data_ultima_alteracao,
    address_logradouro,
    address_numero,
    address_complemento,
    address_bairro,
    address_cidade,
    address_uf,
    address_cep
) VALUES
(
    uuid_generate_v4(),
    'João Silva',
    'joao.silva@email.com',
    'joao.silva',
    '$2a$10$hashedpassword1',
    NOW(),
    'Rua das Flores',
    '123',
    'Apto 101',
    'Centro',
    'São Paulo',
    'SP',
    '01000-000'
),
(
    uuid_generate_v4(),
    'Maria Souza',
    'maria.souza@email.com',
    'maria.souza',
    '$2a$10$hashedpassword2',
    NOW(),
    'Av. Paulista',
    '1000',
    'Sala 202',
    'Bela Vista',
    'São Paulo',
    'SP',
    '01310-100'
),
(
    uuid_generate_v4(),
    'Carlos Pereira',
    'carlos.pereira@email.com',
    'carlos.pereira',
    '$2a$10$hashedpassword3',
    NOW(),
    'Rua Augusta',
    '500',
    NULL,
    'Consolação',
    'São Paulo',
    'SP',
    '01305-000'
);