spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/db_foodlink
    username: postgres
    password: postgres

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    secret: "7l6s9xkwmksUzFPGvbNu6mQ3x0qVY6mkVgQDqToK4T0p/gpMRdxYQjovChb2xD5hE+vtVbJPU8dzcW20b+lWtw=="
    expiration-minutes: 60