server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_foodlink
    username: postgres
    password: postgres

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


